name: Assignment One CI Pipeline
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - name: Run linter
      run: npm run test-lint --prefix src
        
  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - name: run unit test
      run: npm run test-unit --prefix src
      - if: github.ref == 'refs/heads/feature/artefacts'
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-${{ github.sha }}
        path: reports/report.xml

  artifacts:
    runs-on: ubuntu-latest
    if: false
    if: github.ref == 'refs/heads/feature/artefacts'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - if: github.ref == 'refs/heads/feature/artefacts'
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-${{ github.sha }}
        path: reports/report.xml
    
    
    