name: Assignment One CI Pipeline
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - name: Run linter
      run: npm run test-lint --prefix src
        
  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - name: run unit test
      run: npm run test-unit --prefix src
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
         name: coverage-${{ github.sha }}
         path: src/coverage
    - if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-${{ github.sha }}
        path: src/reports/report.xml
        
  e2e-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Installs dependencies
      working-directory: ./src
      run: npm clean-install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Starting the server
      working-directory: ./src
      run: npm start &
    - name: Run E2E tests
      run: npm run test-e2e --prefix src
    - name: Uploads E2E report
      uses: actions/upload-artifact@v3
      if: failure()
      with:
         name: e2e-test-${{ github.sha }}
         path: src/reports/e2e
    - name: Stoping the server
      run: kill $(lsof -t -i:3000)
