name: Assignment One CI Pipeline
on:
  push:
    branches:
    - main
    - feature/add-pipeline
  pull_request:
    branches:
    - main
    - feature/add-pipeline
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Install dependencies
      working-directory: ./src
      run: npm clean-install
    - name: Run linter
      run: npm run test-lint --prefix src
    - name: run unit test
      run: npm run test-unit --prefix src
    - name: Intergration Testing
      run: npm run test-integration --prefix src
